### PR TITLE
TOC for Java

### PR DESCRIPTION
**Pull request by Gyan172004**
### Table of Content for Java Programs

Included TOC having
-Programs(with embedded links)
-Description
-Expected Output
-Actual Output
-If same Program in other language

## Language

- [x] Java
- [ ]  Rust
- [ ] C
- [ ] C++
- [ ] Python
- [ ] Bash
- [ ] JS

### CODE REVIEW

**Comment by Gyan172004** [comment]
Solves #3

**Comment by rootCircle** [comment]
Congrats on your first PR to this repo!

**Comment by rootCircle** [comment]
Can you convert expected/actual output inside a code block to fix formatting issues, maybe?

**Comment by rootCircle** [comment]
Content looks really great for now! Good job!

**Comment by rootCircle** [comment]
Can you check the style output in the README,please https://github.com/Gyan172004/WhyTheHeck/blob/javamd/Java/toc.md ?

**Comment by Gyan172004** [comment]
I tried improving styles in TOC.md file but I think github doesnot support styling.

**Comment by rootCircle** [comment]
Ok, well for now, I am merging it for now, Congrats on your first PR @Gyan172004 :tada:

**Pull request merged**
