### PR TITLE
Add bubble sort buggy code

### PR DESCRIPTION
**Pull request by amansheoran15**
Buggy code for bubble sort.

The code sorts array in descending order instead of sorting it in ascending order.

### CODE REVIEW

**Comment by rootCircle** [comment]
Hi @amansheoran15, congrats on your first PR to this repo! :tada: 

Before, I can start the process of review, can you please revert back the name changes in the `nextline.java` file, please!

**Comment by amansheoran15** [comment]
Please check

**Comment by rootCircle** [comment]
I have pushed in the changes to rename the className!

**Comment by rootCircle** [comment]
Code looks good to me! I request you to put up an entry in here for your code in https://github.com/rootCircle/WhyTheHeck/blob/main/Java/TOC.md

**Comment by amansheoran15** [comment]
Please Review

**Comment by rootCircle** [comment]
LGTM :+1: Merged

Congrats on your first merged PR in this repo :tada:

**Pull request merged**
